// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD545_ffz9SRDcVB0-hUIAam4oPt7LruIY',
    appId: '1:535526992168:web:53e56e6ae443044d4e881d',
    messagingSenderId: '535526992168',
    projectId: 'ygca-cricket-academy',
    authDomain: 'ygca-cricket-academy.firebaseapp.com',
    storageBucket: 'ygca-cricket-academy.firebasestorage.app',
    measurementId: 'G-VHXPW04M36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsu9biA4gBwiQvsa8lALW_oLvbtUOQ0aQ',
    appId: '1:535526992168:android:bd54f917fa4ec97d4e881d',
    messagingSenderId: '535526992168',
    projectId: 'ygca-cricket-academy',
    storageBucket: 'ygca-cricket-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP4zAaWBEUDVdJtwHdMyeTWag3EkD2mvI',
    appId: '1:535526992168:ios:b4b525cb9e07a6ff4e881d',
    messagingSenderId: '535526992168',
    projectId: 'ygca-cricket-academy',
    storageBucket: 'ygca-cricket-academy.firebasestorage.app',
    iosBundleId: 'com.example.ygcaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP4zAaWBEUDVdJtwHdMyeTWag3EkD2mvI',
    appId: '1:535526992168:ios:b4b525cb9e07a6ff4e881d',
    messagingSenderId: '535526992168',
    projectId: 'ygca-cricket-academy',
    storageBucket: 'ygca-cricket-academy.firebasestorage.app',
    iosBundleId: 'com.example.ygcaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD545_ffz9SRDcVB0-hUIAam4oPt7LruIY',
    appId: '1:535526992168:web:023f24c8fe16c6004e881d',
    messagingSenderId: '535526992168',
    projectId: 'ygca-cricket-academy',
    authDomain: 'ygca-cricket-academy.firebaseapp.com',
    storageBucket: 'ygca-cricket-academy.firebasestorage.app',
    measurementId: 'G-QH0YNDG36E',
  );
}
